# Generated by Django 5.1.7 on 2025-03-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descriotion',
            field=models.TimeField(blank=True, null=True, verbose_name='descriotion'),
        ),
    ]
