# Generated by Django 5.1.7 on 2025-03-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_descriotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriotion',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TimeField(blank=True, null=True, verbose_name='description'),
        ),
    ]
