# Generated by Django 5.1.7 on 2025-03-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_descriotion_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descriotion',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TimeField(blank=True, null=True, verbose_name='description'),
        ),
    ]
